# Etapa 1: Construcción
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

# Etapa 2: Servidor Web
FROM nginx:alpine
# Copiamos el build de Angular a la carpeta pública de Nginx
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
# Copiamos configuración para que el routing de Angular no falle
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80